export const speciesMerged = {
  "walleye":"walleye",
  "sauger":"walleye",
  "northern pike":"northern pike",
  "muskellunge":"muskellunge",
  "tiger muskellunge":"tiger muskellunge",
  "channel catfish":"channel catfish",
  "flathead catfish":"flathead catfish",
  "smallmouth bass":"smallmouth bass",
  "largemouth bass":"largemouth bass",
  "white bass":"white bass",
  "rock bass":"rock bass",
  "black crappie":"crappie",
  "white crappie":"crappie",
  "bluegill sunfish":"sunfish",
  "pumpkinseed sunfish":"sunfish",
  "hybrid sunfish":"sunfish",
  "sunfish":"sunfish",
  "green sunfish":"sunfish",
  "yellow perch":"yellow perch",
  "brown bullhead":"bullhead",
  "black bullhead":"bullhead",
  "yellow bullhead":"bullhead",
  "lake trout":"lake trout",
  "brown trout":"brown trout",
  "brook trout":"brook trout",
  "rainbow trout":"rainbow trout",
  "lake sturgeon":"lake sturgeon",
  "lake whitefish":"lake whitefish",
  "burbot":"burbot",
  "bowfin (dogfish)":"bowfin (dogfish)",
  "white sucker":"carp",
  "shorthead redhorse":"carp",
  "common carp":"carp",
  "golden redhorse":"carp",
  "bigmouth buffalo":"carp",
  "silver redhorse":"carp",
  "greater redhorse":"carp"
}
