const speciesCodes = {
  "WAE":"walleye",
  "SAR":"walleye",
  "NOP":"northern pike",
  "MUE":"muskellunge",
  "TME":"tiger muskellunge",
  "CCF":"channel catfish",
  "FCF":"flathead catfish",
  "SMB":"smallmouth bass",
  "LMB":"largemouth bass",
  "WHB":"white bass",
  "RKB":"rock bass",
  "BLC":"crappie",
  "WHC":"crappie",
  "BLG":"sunfish",
  "PMK":"sunfish",
  "HSF":"sunfish",
  "SUN":"sunfish",
  "GSF":"sunfish",
  "YEP":"yellow perch",
  "BRB":"bullhead",
  "BLB":"bullhead",
  "YEB":"bullhead",
  "LAT":"lake trout",
  "BNT":"brown trout",
  "BKT":"brook trout",
  "RBT":"rainbow trout",
  "LKS":"lake sturgeon",
  "LKW":"lake whitefish",
  "BUB":"burbot",
  "BOF":"bowfin (dogfish)",
  "WTS":"carp",
  "SHR":"carp",
  "CAP":"carp",
  "GLR":"carp",
  "BIB":"carp",
  "SLR":"carp",
  "GRR":"carp"
};
